FROM golang:1.21rc3-alpine3.17

# EXPOSE 10123 10123
WORKDIR /app
COPY . ./

RUN CGO_ENABLED=0 go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

ENV GO111MODULE=off
RUN CGO_ENABLED=0 go build -gcflags "all=-N -l" -o sendthing-app .

EXPOSE 12349
CMD [ "/go/bin/dlv", "--listen=:12349", "--headless=true", "--log=true", "--accept-multiclient", "--api-version=2", "exec", "/app/sendthing-app" ]
# CMD [ "./sendthing-app" ]